name       : python-websocket-client
version    : 0.37.0
release    : 1
source     :
    - https://pypi.python.org/packages/a3/1e/b717151e29a70e8f212edae9aebb7812a8cae8477b52d9fe990dcaec9bbd/websocket_client-0.37.0.tar.gz : 678b246d816b94018af5297e72915160e2feb042e0cde1a9397f502ac3a52f41
license    : LGPL-2.0
component  : programming.python
summary    : Websocket client for python
description: Websocket client for python
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup    
install    : |
    %python_install
    %python3_install
