name       : python-websocket-client
version    : 0.56.0
release    : 6
source     :
    - https://github.com/websocket-client/websocket-client/archive/v0.56.0.tar.gz : b70469fe5823c65f2b9ecb065ea7218598de9b80b72cb142281c4b47fcb87032
license    : BSD-3-Clause
component  : programming.python
summary    : Websocket client for python
description: |
    The websocket-client module is WebSocket client for python. It provides the low level APIs for WebSocket. All APIs are the synchronous functions.
builddeps  :
    - pkgconfig(python3)
    - python-backports.ssl_match_hostname
    - python-setuptools
rundeps    :
    - python-backports.ssl_match_hostname
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%}3"
    done
    %python_install

    # remove tests that got installed into the buildroot
    rm -r $installdir/usr/lib/python?.?/site-packages/websocket/tests/
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd

    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd
