name       : python-websocket-client
version    : 0.44.0
release    : 2
source     :
    - https://pypi.python.org/packages/06/19/f00725a8aee30163a7f257092e356388443034877c101757c1466e591bf8/websocket_client-0.44.0.tar.gz : 15f585566e2ea7459136a632b9785aa081093064391878a448c382415e948d72
license    : LGPL-3.0
component  : programming.python
summary    : Websocket client for python
description:
    The websocket-client module is WebSocket client for python. It provides the low level APIs for WebSocket. All APIs are the synchronous functions.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*.py; do
      mv -v "$_f" "${_f%}3"
    done
    %python_install
