name       : python-websocket-client
version    : 1.2.1
release    : 10
source     :
    - https://github.com/websocket-client/websocket-client/archive/refs/tags/v1.2.1.tar.gz : 8e056ff93c85b1961234d1c36fda8c5277a03f1ba475d93afb8ec46d2a7976de
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Websocket client for python
description: |
    The websocket-client module is WebSocket client for python. It provides the low level APIs for WebSocket. All APIs are the synchronous functions.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
    # remove tests that got installed into the buildroot
    rm -r $installdir/usr/lib/python?.?/site-packages/websocket/tests/
#check      : |
#    %python3_test
