name       : python-websocket-client
version    : 0.57.0
release    : 7
source     :
    - https://github.com/websocket-client/websocket-client/archive/v0.57.0.tar.gz : 95ad4af67fe32f292884553e508997e10a4b3cd61d4abf122aebef7c645cd189
license    : BSD-3-Clause
component  : programming.python
summary    : Websocket client for python
description: |
    The websocket-client module is WebSocket client for python. It provides the low level APIs for WebSocket. All APIs are the synchronous functions.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
    # remove tests that got installed into the buildroot
    rm -r $installdir/usr/lib/python?.?/site-packages/websocket/tests/
check      : |
    %python3_test
